# Generated by Django 5.1.1 on 2024-09-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_product_image_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sub",
                to="shop.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
