# Generated by Django 5.1.1 on 2024-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_cartitem_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Сумма по продукту"
            ),
        ),
    ]
