# Generated by Django 5.1.1 on 2024-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_delete_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=200)),
                ("product_price", models.FloatField()),
                ("product_quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
